package view.form;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import model.Form;

public class Bieumau extends javax.swing.JPanel {

    private final JPopupMenu popupMenu;
    private String name;
    private int id;

    public int getId() {
        return this.id; // Trả về ID của biểu mẫu
    }

    private final Form form;
    
    public Bieumau(Form form) {
        this.form = form;
        initComponents();
        // Khởi tạo JPopupMenu
        popupMenu = new JPopupMenu();
        popupMenu.setPreferredSize(new java.awt.Dimension(110, 60));

        JMenuItem renameItem = new JMenuItem("Đổi tên");
        renameItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDoitenPanel();
            }
        });

        JMenuItem deleteItem = new JMenuItem("Xóa");
        deleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showXoaPanel();
            }
        });

        popupMenu.add(renameItem);
        popupMenu.add(deleteItem);
        
        nameFormLabel.setText(form.getFormName());

    }

    public Form getForm() {
        return form;
    }

    
    
    private void showDoitenPanel() {

        JFrame frame = new JFrame("Đổi tên");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Truyền tham chiếu của Bieumau vào Doiten
        Doiten doitenPanel = new Doiten(this.getId(), this);
        frame.getContentPane().add(doitenPanel);
        frame.pack();
        frame.setLocationRelativeTo(null); // Căn giữa màn hình
        frame.setVisible(true);
    }

    private void showXoaPanel() {
        JFrame frame = new JFrame("Xóa");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(new Xoa(this));
        frame.pack();
        frame.setLocationRelativeTo(null); // Căn giữa màn hình
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameFormLabel = new javax.swing.JLabel();
        myButton1 = new main_style.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(90, 110));
        setMinimumSize(new java.awt.Dimension(90, 110));
        setPreferredSize(new java.awt.Dimension(90, 110));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        nameFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameFormLabel.setText("Biểu mẫu A");
        nameFormLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3844442_dot_menu_more_vertical_icon.png"))); // NOI18N
        myButton1.setBorderColor(new java.awt.Color(204, 204, 204));
        myButton1.setColor(new java.awt.Color(204, 204, 204));
        myButton1.setColorOver(new java.awt.Color(255, 255, 255));
        myButton1.setMargin(new java.awt.Insets(26, 26, 26, 26));
        myButton1.setMaximumSize(new java.awt.Dimension(25, 25));
        myButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        myButton1.setPreferredSize(new java.awt.Dimension(25, 25));
        myButton1.setRadius(100);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameFormLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(nameFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        popupMenu.show(myButton1, 0, myButton1.getHeight());

        // Lấy id của biểu mẫu
        int formId = this.getId();
        System.out.println("ID của biểu mẫu là: " + formId);
    }//GEN-LAST:event_myButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        FormInfo formInfo = new FormInfo(this);
        formInfo.setVisible(true);
    }//GEN-LAST:event_formMouseClicked
    public void removeForm() {
        // Xóa biểu mẫu này khỏi giao diện
        this.setVisible(false); // Ẩn biểu mẫu
        this.getParent().remove(this); // Xóa biểu mẫu khỏi panel cha
    }

    public void setId(int id) {
        this.id = id;
        System.out.println("ID được gán là: " + this.id); // Hiển thị ID được gán
    }

    public void setName(String name) {
        this.name = name;
        nameFormLabel.setText(name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private main_style.MyButton myButton1;
    private javax.swing.JLabel nameFormLabel;
    // End of variables declaration//GEN-END:variables
}
