/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.sample;

import database.DatabaseConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import model.SampleRecord;
import model.SampleRecordValue;

/**
 *
 * @author chuna
 */
public class EditSample extends javax.swing.JFrame {

    /**
     * Creates new form EditSample
     */
    public EditSample() {
        initComponents();
        authorSampleTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        myButton1 = new main_style.MyButton();
        cancelEditedButton = new main_style.MyButton();
        saveChangeButton = new main_style.MyButton();
        nameSampleTextField = new main_style.RoundTextField();
        locateSampleTextField = new main_style.RoundTextField();
        authorSampleTextField = new main_style.RoundTextField();
        reasonSampleTextField = new main_style.RoundTextField();
        jLabel7 = new javax.swing.JLabel();
        IdSamplesComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        jLabel2.setText("Tên mẫu");

        jLabel3.setText("Vị trí");

        jLabel4.setText("Người thu mẫu");

        jLabel5.setText("Lý do thu mẫu");

        jLabel6.setText("Mẫu");

        myButton1.setBorder(null);
        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/upload_icon.png"))); // NOI18N
        myButton1.setText("Tải lên từ máy");
        myButton1.setBorderColor(new java.awt.Color(204, 255, 204));
        myButton1.setColorOver(new java.awt.Color(152, 184, 144));
        myButton1.setMaximumSize(new java.awt.Dimension(124, 34));
        myButton1.setMinimumSize(new java.awt.Dimension(124, 34));
        myButton1.setPreferredSize(new java.awt.Dimension(124, 34));
        myButton1.setRadius(30);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        cancelEditedButton.setBackground(new java.awt.Color(0, 204, 153));
        cancelEditedButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelEditedButton.setText("Hủy");
        cancelEditedButton.setBorderColor(new java.awt.Color(0, 204, 153));
        cancelEditedButton.setColor(new java.awt.Color(0, 204, 153));
        cancelEditedButton.setColorClick(new java.awt.Color(0, 211, 153));
        cancelEditedButton.setColorOver(new java.awt.Color(0, 212, 153));
        cancelEditedButton.setDefaultCapable(false);
        cancelEditedButton.setRadius(30);
        cancelEditedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditedButtonActionPerformed(evt);
            }
        });

        saveChangeButton.setBackground(new java.awt.Color(0, 204, 153));
        saveChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        saveChangeButton.setText("Lưu");
        saveChangeButton.setBorderColor(new java.awt.Color(0, 204, 153));
        saveChangeButton.setColor(new java.awt.Color(0, 204, 153));
        saveChangeButton.setColorClick(new java.awt.Color(0, 211, 153));
        saveChangeButton.setColorOver(new java.awt.Color(0, 212, 153));
        saveChangeButton.setRadius(30);
        saveChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangeButtonActionPerformed(evt);
            }
        });

        nameSampleTextField.setBorderColor(new java.awt.Color(153, 255, 153));
        nameSampleTextField.setCornerRadius(30);
        nameSampleTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        nameSampleTextField.setMinimumSize(new java.awt.Dimension(64, 34));
        nameSampleTextField.setPreferredSize(new java.awt.Dimension(64, 34));

        locateSampleTextField.setBorderColor(new java.awt.Color(153, 255, 153));
        locateSampleTextField.setCornerRadius(30);
        locateSampleTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        locateSampleTextField.setMinimumSize(new java.awt.Dimension(64, 34));
        locateSampleTextField.setPreferredSize(new java.awt.Dimension(64, 34));

        authorSampleTextField.setBorderColor(new java.awt.Color(153, 255, 153));
        authorSampleTextField.setCornerRadius(30);
        authorSampleTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        authorSampleTextField.setMinimumSize(new java.awt.Dimension(64, 34));
        authorSampleTextField.setPreferredSize(new java.awt.Dimension(64, 34));

        reasonSampleTextField.setBorderColor(new java.awt.Color(153, 255, 153));
        reasonSampleTextField.setCornerRadius(30);
        reasonSampleTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        reasonSampleTextField.setMinimumSize(new java.awt.Dimension(64, 34));
        reasonSampleTextField.setPreferredSize(new java.awt.Dimension(64, 34));

        jLabel7.setText("ID mẫu");

        IdSamplesComboBox.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelEditedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(saveChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(authorSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(myButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(reasonSampleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(nameSampleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(locateSampleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(IdSamplesComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdSamplesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locateSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(authorSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(reasonSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelEditedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHỈNH SỬA MẪU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 374, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 84, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Đã chọn tệp: " + selectedFile.getAbsolutePath());

            // Thực hiện hành động tiếp theo
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void cancelEditedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditedButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelEditedButtonActionPerformed

    private void saveChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangeButtonActionPerformed
        Connection conn = DatabaseConnection.getConnection();
        SampleRecord sampleRecord = new SampleRecord();
        int selectedId = Integer.parseInt((String) IdSamplesComboBox.getSelectedItem());
        sampleRecord.setSampleRecordId(selectedId);

        SampleRecordValue  sampleRecordValue = new SampleRecordValue();
        sampleRecordValue.setSampleRecordId(selectedId);
        String newName = nameSampleTextField.getText(); // Giả sử bạn đã nhập tên mới vào textField
        String newLocation = locateSampleTextField.getText();
        
        String newReason = reasonSampleTextField.getText();
        
        try {
            sampleRecord.updateSampleRecord(conn, newName);
            sampleRecordValue.updateSampleRecordValue(conn, newLocation, newReason);
        } catch (SQLException ex) {
            Logger.getLogger(EditSample.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveChangeButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Connection conn = DatabaseConnection.getConnection();
        SampleRecord sampleRecord = new SampleRecord();
        IdSamplesComboBox.removeAllItems();
        try {
            // Lấy danh sách SampleRecords
            List<SampleRecord> records = sampleRecord.getSampleRecords(conn);
            for (SampleRecord record : records) {
                int sampleId = record.getSampleRecordId();
                IdSamplesComboBox.addItem(String.valueOf(sampleId));
            }

            // Thêm ActionListener cho JComboBox
            IdSamplesComboBox.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int selectedId = Integer.parseInt((String) IdSamplesComboBox.getSelectedItem());
                    try {
                        updateTextFields(conn, selectedId);
                    } catch (SQLException ex) {
                        Logger.getLogger(EditSample.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

            // Cập nhật text fields với mục đầu tiên được chọn
            if (IdSamplesComboBox.getItemCount() > 0) {
                int firstSelectedId = Integer.parseInt((String) IdSamplesComboBox.getItemAt(0));
                updateTextFields(conn, firstSelectedId);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close the connection if needed
        }
    }//GEN-LAST:event_formWindowOpened

    private void updateTextFields(Connection conn, int sampleId) throws SQLException {
        SampleRecord sampleRecord = new SampleRecord();
        sampleRecord.getSampleRecordById(conn, sampleId);
        nameSampleTextField.setText(sampleRecord.getSampleRecordName());

        SampleRecordValue sampleRecordValue = SampleRecordValue.getSampleRecordValueBySampleRecordId(conn, sampleId);
        if (sampleRecordValue != null) {
            locateSampleTextField.setText(sampleRecordValue.getSampleRecordValueLocation());
            authorSampleTextField.setText(sampleRecordValue.getSampleRecordValueAuthor());
            reasonSampleTextField.setText(sampleRecordValue.getSampleRecordValueReason());
        } else {
            // Nếu không có sampleRecordValue, bạn có thể đặt giá trị mặc định hoặc xóa trường
            locateSampleTextField.setText("");
            authorSampleTextField.setText("");
            reasonSampleTextField.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> IdSamplesComboBox;
    private main_style.RoundTextField authorSampleTextField;
    private main_style.MyButton cancelEditedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private main_style.RoundTextField locateSampleTextField;
    private main_style.MyButton myButton1;
    private main_style.RoundTextField nameSampleTextField;
    private main_style.RoundTextField reasonSampleTextField;
    private main_style.MyButton saveChangeButton;
    // End of variables declaration//GEN-END:variables
}
