package view.sample;

import database.DatabaseConnection;
import java.awt.Point;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.SampleRecord;
import model.SampleRecordValue;
import javax.swing.JLabel;
/**
 *
 * @author chuna
 */
public class SampleIcon extends javax.swing.JPanel {

   
     private final SampleRecord sampleRecord;
    public SampleIcon(SampleRecord sampleRecord) {
        this.sampleRecord = sampleRecord;
        initComponents();
        displaySampleRecord();
    }

    private void displaySampleRecord() {
        // Display the sample record's name
        nameSample.setText(sampleRecord.getSampleRecordName());
    }

    public SampleRecord getSampleRecord() {
        return sampleRecord;
    }

    public String getNameSample() {
        return nameSample.getText();
    }

    public void setNameSample(JLabel nameSample) {
        this.nameSample = nameSample;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extendPopupMenu = new javax.swing.JPopupMenu();
        editMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        nameSample = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        extendButton = new main_style.MyButton();

        extendPopupMenu.setMaximumSize(new java.awt.Dimension(80, 50));
        extendPopupMenu.setMinimumSize(new java.awt.Dimension(80, 50));
        extendPopupMenu.setPreferredSize(new java.awt.Dimension(80, 50));

        editMenuItem.setText("Chỉnh sửa");
        editMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuItemActionPerformed(evt);
            }
        });
        extendPopupMenu.add(editMenuItem);

        deleteMenuItem.setText("Xóa");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        extendPopupMenu.add(deleteMenuItem);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(90, 120));
        setMinimumSize(new java.awt.Dimension(90, 120));
        setPreferredSize(new java.awt.Dimension(90, 120));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(69, 90));
        jPanel4.setMinimumSize(new java.awt.Dimension(69, 90));
        jPanel4.setPreferredSize(new java.awt.Dimension(69, 90));

        nameSample.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameSample.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-image-48.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(62, 62));
        jLabel3.setMinimumSize(new java.awt.Dimension(62, 62));
        jLabel3.setPreferredSize(new java.awt.Dimension(62, 62));

        extendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3844442_dot_menu_more_vertical_icon.png"))); // NOI18N
        extendButton.setBorderColor(new java.awt.Color(204, 204, 204));
        extendButton.setColor(new java.awt.Color(204, 204, 204));
        extendButton.setColorOver(new java.awt.Color(255, 255, 255));
        extendButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        extendButton.setMaximumSize(new java.awt.Dimension(26, 26));
        extendButton.setMinimumSize(new java.awt.Dimension(26, 26));
        extendButton.setPreferredSize(new java.awt.Dimension(26, 26));
        extendButton.setRadius(100);
        extendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(extendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameSample, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nameSample, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuItemActionPerformed
        // TODO add your handling code here:
        EditSample editSample = new EditSample();
        editSample.setVisible(true);

    }//GEN-LAST:event_editMenuItemActionPerformed

    private void extendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extendButtonActionPerformed
        // TODO add your handling code here:
        extendPopupMenu.add(editMenuItem);
        extendPopupMenu.add(deleteMenuItem);

        // Lấy vị trí của extendLabel trên màn hình
        Point labelLocationOnScreen = extendButton.getLocationOnScreen();

        // Tính toán vị trí hiển thị menu nằm bên phải của extendLabel
        int popupX = labelLocationOnScreen.x + extendButton.getWidth();
        int popupY = labelLocationOnScreen.y;

        // Hiển thị popup menu tại vị trí tương đối (popupX - labelLocationInContainer.x)
        extendPopupMenu.show(extendButton, popupX - labelLocationOnScreen.x, popupY - labelLocationOnScreen.y);
    }//GEN-LAST:event_extendButtonActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // Remove the sample record from the database
                                               
    // Confirm deletion
    int confirmation = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this Sample Record?", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION);
    
    if (confirmation == JOptionPane.YES_OPTION) {
        try (Connection conn = DatabaseConnection.getConnection()) {
            // Assuming you have a method to delete all SampleRecordValues for a specific SampleRecordId
            SampleRecordValue.deleteAllBySampleRecordId(conn, sampleRecord.getSampleRecordId());
            
            // Delete the sample record itself
            sampleRecord.deleteSampleRecord(conn);
            JOptionPane.showMessageDialog(this, "SampleRecord deleted successfully.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error deleting SampleRecord: " + e.getMessage());
        }

        // Remove this SampleIcon from the parent container
        java.awt.Container parent = this.getParent();
        if (parent != null) {
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        }
    }




    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        SampleInfo sampleInfo = new SampleInfo(this);
        sampleInfo.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem editMenuItem;
    private main_style.MyButton extendButton;
    private javax.swing.JPopupMenu extendPopupMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameSample;
    // End of variables declaration//GEN-END:variables
}
