/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.sample;

import database.DatabaseConnection;
import database.DatabaseOperation;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.SampleRecord;

/**
 *
 * @author chuna
 */
public class SampleIcon extends javax.swing.JPanel {

    /**
     * Creates new form SampleIcon
     */
    public SampleIcon(String sampleRecordName) {
        initComponents();
        nameSample.setText(sampleRecordName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extendPopupMenu = new javax.swing.JPopupMenu();
        editMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nameSample = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        extendButton = new main_style.MyButton();

        extendPopupMenu.setMaximumSize(new java.awt.Dimension(80, 50));
        extendPopupMenu.setMinimumSize(new java.awt.Dimension(80, 50));
        extendPopupMenu.setPreferredSize(new java.awt.Dimension(80, 50));

        editMenuItem.setText("Chỉnh sửa");
        editMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMenuItemMouseClicked(evt);
            }
        });
        editMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuItemActionPerformed(evt);
            }
        });
        extendPopupMenu.add(editMenuItem);

        deleteMenuItem.setText("Xóa");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        extendPopupMenu.add(deleteMenuItem);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(90, 120));
        setMinimumSize(new java.awt.Dimension(90, 120));
        setPreferredSize(new java.awt.Dimension(90, 120));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(69, 90));
        jPanel4.setMinimumSize(new java.awt.Dimension(69, 90));
        jPanel4.setPreferredSize(new java.awt.Dimension(69, 90));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2674094_object_image_file_web_essential_icon.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(62, 62));
        jLabel3.setMinimumSize(new java.awt.Dimension(62, 62));
        jLabel3.setPreferredSize(new java.awt.Dimension(62, 62));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(80, 25));
        jPanel5.setMinimumSize(new java.awt.Dimension(80, 25));
        jPanel5.setPreferredSize(new java.awt.Dimension(80, 25));

        nameSample.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameSample.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(nameSample, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(nameSample, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(26, 90));
        jPanel6.setMinimumSize(new java.awt.Dimension(26, 90));
        jPanel6.setPreferredSize(new java.awt.Dimension(26, 90));

        extendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3844442_dot_menu_more_vertical_icon.png"))); // NOI18N
        extendButton.setBorderColor(new java.awt.Color(255, 255, 255));
        extendButton.setColorOver(new java.awt.Color(255, 255, 255));
        extendButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        extendButton.setMaximumSize(new java.awt.Dimension(26, 26));
        extendButton.setMinimumSize(new java.awt.Dimension(26, 26));
        extendButton.setPreferredSize(new java.awt.Dimension(26, 26));
        extendButton.setRadius(100);
        extendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(extendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(extendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel6, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void editMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuItemActionPerformed
        // TODO add your handling code here:
        EditSample editSample = new EditSample();
        editSample.setVisible(true);

    }//GEN-LAST:event_editMenuItemActionPerformed

    private void extendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extendButtonActionPerformed
        // TODO add your handling code here:
        extendPopupMenu.add(editMenuItem);
        extendPopupMenu.add(deleteMenuItem);

        // Lấy vị trí của extendLabel trên màn hình
        Point labelLocationOnScreen = extendButton.getLocationOnScreen();

        // Tính toán vị trí hiển thị menu nằm bên phải của extendLabel
        int popupX = labelLocationOnScreen.x + extendButton.getWidth();
        int popupY = labelLocationOnScreen.y;

        // Hiển thị popup menu tại vị trí tương đối (popupX - labelLocationInContainer.x)
        extendPopupMenu.show(extendButton, popupX - labelLocationOnScreen.x, popupY - labelLocationOnScreen.y);
    }//GEN-LAST:event_extendButtonActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        //Connection conn = DatabaseConnection.getConnection();
        
        java.awt.Container parent = this.getParent();
    
    if (parent != null) {
        // Xóa panel hiện tại ra khỏi container
        parent.remove(this);
        
        // Cập nhật lại giao diện
        parent.revalidate();
        parent.repaint();
    }


    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void editMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_editMenuItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem editMenuItem;
    private main_style.MyButton extendButton;
    private javax.swing.JPopupMenu extendPopupMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel nameSample;
    // End of variables declaration//GEN-END:variables
}
